In [1]:
import numpy as np
from scipy.optimize import curve_fit
from scipy.integrate import quad
from scipy.stats import norm
from scipy import stats

# 1. Data Modeling and Fitting

In [2]:
# Creating a function to model and create data
def func(x, a, b):
    return a * x + b

In [3]:
# Generating clean data
x = np.linspace(0, 10, 100)
y = func(x, 1, 2)

In [4]:
# Adding noise to the data
yn = y + 0.9 * np.random.normal(size=len(x))

In [5]:
# Executing curve_fit on noisy data
popt, pcov = curve_fit(func, x, yn)

In [6]:
# popt returns the best fit values for parameters of the given model (func).
popt

array([ 0.98517454,  2.02463022])

In [7]:
# the diagonal elements are the variances for each parameter
pcov

array([[ 0.00101729, -0.00508644],
       [-0.00508644,  0.03408089]])

# 2. Analytic Integration

$$\int_0^3cos(e^x)^2dx$$

In [8]:
# Defining function to integrate
func = lambda x: np.cos(np.exp(x)) ** 2

In [9]:
# Integrating function with upper and lower limits of 0 and 3, respectively
solution = quad(func, 0, 3)

In [10]:
# The first element is the desired value and the second is the error.
print solution

(1.296467785724373, 1.397797186265988e-09)


# 3. Continuous and Discrete Distributions

In [11]:
x = np.linspace(-5,5,10)

In [12]:
# set up the parameters for the normal distribution,
# where loc is the mean and scale is the standard deviation.
dist = norm(loc=0, scale=1)

In [13]:
# Retrieving norm's PDF (probability density functions)
pdf = dist.pdf(x)
pdf

array([  1.48671951e-06,   2.07440309e-04,   8.42153448e-03,
         9.94771388e-02,   3.41892294e-01,   3.41892294e-01,
         9.94771388e-02,   8.42153448e-03,   2.07440309e-04,
         1.48671951e-06])

In [14]:
# Retrieving norm's CDF (cumulative distribution functions)
cdf = dist.cdf(x)
cdf

array([  2.86651572e-07,   5.03521029e-05,   2.73660179e-03,
         4.77903523e-02,   2.89257361e-01,   7.10742639e-01,
         9.52209648e-01,   9.97263398e-01,   9.99949648e-01,
         9.99999713e-01])

In [15]:
# draw out 5 random variable samples (RVSs)
sample = dist.rvs(5)
sample

array([-0.81955862, -0.10467463, -1.0977978 , -0.07817924,  1.45724529])

# 4. Distribution tests

In [16]:
# Generating a normal distribution sample with 100 elements
sample = np.random.randn(100)

In [17]:
# normaltest tests the null hypothesis that a sample comes from a normal distribution.
out = stats.normaltest(sample)
print('normaltest output')
print('Z-score = ' + str(out[0]))
print('P-value = ' + str(out[1]))

normaltest output
Z-score = 1.27408059959
P-value = 0.528855363313


In [18]:
# kstest is the Kolmogorov-Smirnov test for goodness of fit.
# Here its sample is being tested against the normal distribution.
# D is the KS statistic and the closer it is to 0 the better.
out = stats.kstest(sample, 'norm')
print('\nkstest output for the Normal distribution')
print('D = ' + str(out[0]))
print('P-value = ' + str(out[1]))


kstest output for the Normal distribution
D = 0.217858896535
P-value = 0.000120043178572


In [19]:
# It can be easily tested against other distributions, like the Wald distribution.
out = stats.kstest(sample, 'wald')
print('\nkstest output for the Wald distribution')
print('D = ' + str(out[0]))
print('P-value = ' + str(out[1]))


kstest output for the Wald distribution
D = 0.739878272254
P-value = 0.0


# 5. Descriptive functions

In [20]:
# Generating a normal distribution sample with 100 elements
sample = np.random.randn(100)

In [21]:
# The harmonic mean: Sample values have to be greater than 0.
out = stats.hmean(sample[sample > 0])
print('Harmonic mean = ' + str(out))

Harmonic mean = 0.253934091784


In [22]:
# The mean, where values below -1 and above 1 are removed for the mean calculation
out = stats.tmean(sample, limits=(-1, 1))
print('\nTrimmed mean = ' + str(out))


Trimmed mean = 0.0611201858187


In [23]:
# The geometric mean: Sample values have to be greater than 0.
out = stats.gmean(sample[sample>0])
print('Geometric mean = ' + str(out))

Geometric mean = 0.473754118731


In [24]:
# Calculating the skewness of the sample
out = stats.skew(sample)
print('\nSkewness = ' + str(out))


Skewness = -0.132560299012


In [25]:
# Additionally, there is a handy summary function called describe, which gives a quick look at the data.
out = stats.describe(sample)
print('\nSize = ' + str(out[0]))
print('Min = ' + str(out[1][0]))
print('Max = ' + str(out[1][1]))
print('Mean = ' + str(out[2]))
print('Variance = ' + str(out[3]))
print('Skewness = ' + str(out[4]))
print('Kurtosis = ' + str(out[5]))


Size = 100
Min = -2.68925512779
Max = 2.61237957079
Mean = 0.0640264178895
Variance = 0.841553145306
Skewness = -0.132560299012
Kurtosis = 0.0874784069543
